### PR TITLE
Mqtt in dev

### PR DESCRIPTION
**Pull request by jontio**
Really have to merge this into master now else I'll forget to do it. There are a few things as I recall about the build scripts that I was planning to fix for the new Debian packages but that will have to wait for a later time.

### CODE REVIEW

**Comment by kevinelliott** [comment]
Hey @jontio ! From what I can tell, this is sending ordered byte arrays, is that correct? Is there a chance we can have the JSON format? That is more universal and supported, and opens up a lot more simplistic interaction with the data. I mean, if the data can be sent in a more convenient object format, that would be very helpful, even if there's a message size overhead.

**Comment by jontio** [comment]
Hi @kevinelliott . As I recall there is a raw output of the su that you might be talking about but dealing with sus is a layer below acars so is probably not much use to anyone. The current master head and the development build has the option to output acars data in a json format to udp or mqtt. mqtt only outputs json while udp you have to change the acars window format in the settings dialog,

**Comment by kevinelliott** [comment]
Hey @jontio thanks for the quick reply friend! I took a look at the merged code and my impression is that it's only byte array serialization to MQTT. Am I wrong? (Would love to be wrong :))

**Comment by jontio** [comment]
@kevinelliott , just had a look and it looks like your right. It seems with mqtt I'm storing things as qbytearrays and then compressing them. Bother I thought I had made the mqtt messages as json format. I guess currently there are two work arounds, one would be having another jaero instance connecting to the mqtt broker decoding the compressed qbytearrays then getting that jaero to output json to a udp port. The other option using something like node red connected to the udp json output and getting that to send that on to a mqtt broker. I think the second option is how I'm doing the websockets example https://jontio.zapto.org/jaero_ws/ . But yes your right a sjon format for mqtt would be nice.

**Comment by thebaldgeek** [comment]
@jontio Just back to your first reply to this MQTT topic Jonti..... There are many of us looking to get a data feed of the SU tab.
It sounds like there might be a way to do that and to get Node-RED to give us a JSON feed?

Regarding your second reply, I will test running 2 Jaero 'in series', the first sending data to MQTT, the second decoding it as JSON.
I need to run my first Jaero as it has been for many years (String output) since my whole website is built around that, but @kevinelliott new Airframes.io website is built around JSON, we are looking to somehow feed both sites with C and L Band data.
(And somehow get a raw feed from the SU tab from Jaero).

**Comment by jontio** [comment]
@thebaldgeek the su tab info as I recall can be outputted if you click the following icons...
image
but the sus are fragments of other things like acars messages so would require work to make any use with them. If you did want the su tab in json format node red should be able to do that. The su data only appears if your using zmq or audio inputs not mqtt input.

**Comment by cesardxmx** [comment]
Hi, I don't have much experience compiling source code on linux. I have tried to build JAERO for a raspberry pi running Raspberry Pi OS 64bits (ARM, aarch64) using the pi-build script but get a missing package error, qt5-default. 
Is there a solution to this error?

**Comment by thebaldgeek** [comment]
@cesardxmx I spent about 4 or 5 days doing build after build trying to get it sorted and somewhat got there, my notes are a bit of a mess. In the end, I just went with DragonOS for Pi and it works minutes after burning the SD card. 
Got a bunch of people using that distro with Jaero and are very happy.
The nice thing is that SDRReceiver is also on the distro and the two work together so well its amazing how a Pi 4 can support around 12 Jaeros. If you do manage to build it from source, you will struggle to run 4-6 instances at most.
Notes for running both are on my github.

**Comment by cesardxmx** [comment]
Ok. Thanks! Gracias!

**Pull request merged**
