### PR TITLE
Free beep when not used

### PR DESCRIPTION
**Pull request by vladisslav2011**
Saves one audio stream per JAERO instance
Close https://github.com/jontio/JAERO/issues/78

### CODE REVIEW

**Comment by jontio** [comment]
I hear that using `delete` for qt objects can be risky and they recommend to use the `deletelater` signal instead. what do you think?

**Comment by vladisslav2011** [comment]
If we are not passing a parent object to the constructor and not using the object in another thread, then deleting it with `delete` should be safe.
Anyways, I think, that using `deleteLater()` (and passing parent object to a constructor) may be better. I'll check if `deleteLater()` and construction with a parent works as required and update the PR.

**Comment by vladisslav2011** [comment]
`deleteLater()` works too.

**Comment by jontio** [comment]
Thanks. I think that should be ok. I'll merge that into master.

**Pull request merged**
